# Site settings
title: La era del reloj inteligente
email: smartwatcha@smart.com
description: > # this means to ignore newlines until "baseurl:"
  Un reloj inteligente es un aparato tecnológico de pulsera que posee funcionalidades 
  que van mas allá de las de un reloj y que hacen de él un dispositivo móvil multifunción. 

baseurl: "/example" # the subpath of your site, e.g. /blog/
url: "http://jekyll.github.io" # the base hostname & protocol for your site
twitter_username: albertomrtn
github_username:  alu0100836950

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

collections:
  - character

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal